spring:
  application:
    name: servicio-api-gateway
  cloud:
    gateway:
      routes:
       - id: servicio-prueba
         uri: lb://servicio-prueba
         predicates:
           - Path=/redis/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://eureka-server:8761/eureka/
      
instance:
   hostname: servicio-api-gateway
server:
  port: 9980
