spring:
  application:
    name: servicio-api-gateway
    
spring:
  server:
    port: 9093
  
 
eureka:
  instance:
    appname: servicio-documentacion
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://SERVICIO-EUREKA:8761/eureka/
      
swagger: 
  config: 
    refreshrate: 5000
