server:
  port: 9981

spring:
  application:
    name: servicio-api-gateway
  cloud:
    gateway:
      routes:
       - id: servicio-redis
         uri: lb://servicio-redis
         predicates:
           - Path=/redis/**
   

