spring:
  application:
    name: servicio-api-gateway
  cloud:
    gateway:
      routes:
       - id: servicio-redis
         uri: lb://servicio-redis
         predicates:
           - Path=/redis/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://servicio-eureka:8761/eureka/
      
   instance:
       instance-id : ${spring.application.name}:${spring.application.instance_id:9980}
  
   
server:
  port: 9980
