server:
  port: 9093
  
 
eureka:
  instance:
    appname: documentation-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.9:8761/eureka/
      
swagger: 
  config: 
    refreshrate: 5000
