server:
  port: 9980

spring:
  application:
    name: servicio-api-gateway
  cloud:
    gateway:
      routes:
       - id: prueba-server
         uri: lb://prueba-server
         predicates:
           - Path=/redis/**
   

